### ISSUE TITLE
Add Scrutor AsSelf() functionality

### ISSUE THREAD

**Issue by Genmutant** [Dreamescaper/ServiceScan.SourceGenerator#5]
I need to register some classes as themself. They can be found by a specific interface, but I don't want to register them as such, as the specific implementations need to be injected.

If I understand correctly, this is currently not possible?

**Comment by Dreamescaper** [comment]
Currently not, but I already have a branch with this functionality, only need to clean it up a bit. 
Will let you know once it's published.

**Comment by Dreamescaper** [comment]
@Genmutant 
I've published updated nuget package:
https://www.nuget.org/packages/ServiceScan.SourceGenerator/1.1.2

Now you can use AsSelf flag:
```csharp
[GenerateServiceRegistrations(AssignableTo = typeof(IService), AsSelf = true)]
```
or
```csharp
[GenerateServiceRegistrations(AssignableTo = typeof(IService), AsSelf = true, AsImplementedInterfaces = true)]
```

**Comment by Genmutant** [comment]
Works great, thanks!
